### ISSUE TITLE
The dataset link is not available.

### ISSUE THREAD

**Issue by NougatCA** [pdlan/OSCAR#10]
The given dataset link https://1drv.ms/u/s!AjYwgux2zLgMiAhYpoCU3jLu20Z6?e=XR52y9 is not available. It says that "this item might not exist or is no longer available".

**Comment by huangyifei226** [comment]
> The given dataset link https://1drv.ms/u/s!AjYwgux2zLgMiAhYpoCU3jLu20Z6?e=XR52y9 is not available. It says that "this item might not exist or is no longer available".

Have you solved this problem? I also want to download the dataset, but I failed.T_T

**Comment by NougatCA** [comment]
> > The given dataset link https://1drv.ms/u/s!AjYwgux2zLgMiAhYpoCU3jLu20Z6?e=XR52y9 is not available. It says that "this item might not exist or is no longer available".
> 
> Have you solved this problem? I also want to download the dataset, but I failed.T_T

Now the link is available, I can download it now. You still can't open it now?
